export const GET_DATA_REQUEST = "GET_DATA_REQUEST";
export const GET_DATA_SUCCESS = "GET_DATA_SUCCESS";
export const GET_DATA_FALIURE = "GET_DATA_FALIURE";
export const GET_SELECTED_PRODUCT = "GET_SELECTED_PRODUCT";
